class CHECKOUT_PAGE {
  constructor() {
    this.IMG_LOGO = 'a.checkout-logo'
    this.MODAL_INFO_EMAIL = '.emailInfo'
    this.MODAL_PROFILE_DATA = '#client-profile-data'
    this.TEXT_EMAIL = '.client-profile-email .email'
    this.TEXT_NAME = '.client-profile-summary .name'
    this.INPUT_FIRT_NAME = '#client-first-name'
    this.INPUT_LAST_NAME = '#client-last-name'
    this.INPUT_CPF = '#client-document'
    this.INPUT_PHONE = '#client-phone'
    this.TEXT_TEL = '.client-profile-summary .tel'
    this.BTN_EDIT_ADDRESS = '#force-shipping-fields'
    this.INPUT_STREET = '#ship-street'
    this.BTN_EDIT_PROFILE = '#edit-profile-data > .icon-edit'
    this.TXT_SPAN_EMAIL = '.client-email span'
    this.INPUT_SHIP_NUMBER = '#ship-number'
    this.INPUT_SHIP_NAME = '#ship-receiverName'
    this.BTN_GO_PAYMENT = '#btn-go-to-payment'
    this.MODAL_PAYMENT = '#payment-data > .step'
    this.BTN_PAYMENT_PIX = '#payment-group-instantPaymentPaymentGroup'
    this.BTN_PAYMENT_CARD = '#payment-group-creditCardPaymentGroup'
    this.BTN_PAYMENT_SLIP = '#payment-group-bankInvoicePaymentGroup'
    this.BTN_PAYMENT_EXCHANG = '#show-gift-card-group'
    this.TEXT_PAYMENT_EXCHANG = '.payment-discounts-options > label'
    this.INPUT_PAYMENT_EXCHANG = '#payment-discounts-code'
    this.MODAL_IFRAME_PAYMENT = '.steps-view'
    this.MODAL_IFRAME_PAYMENT_CARD = '#iframe-placeholder-creditCardPaymentGroup > .span12'
    this.TEXT_PAYMENT_PIX = '.payment-pix-description'
    this.MODAL_ORDER_SUMMARY = '.cart-fixed'
    this.BTN_RETORN_CART = '#orderform-minicart-to-cart'
    this.BTN_PAYMENT = '.payment-confirmation-wrap #payment-data-submit'
    this.TEXT_TITLE_CART = '.cart-fixed h2'
    this.TEXT_SUBTOTAL_VALUE = '.totalizers-list .Items .monetary'
    this.TEXT_TOTAL_VALUE = 'tfoot .monetary'
    this.TEXT_SHIPPING_VALUE = '.totalizers-list .Shipping .monetary'
  }
}

module.exports = CHECKOUT_PAGE
