class REGION_PAGE {
  constructor() {
    this.BTN_POSTAL = '#CepButton-ArrowID'
    this.BTN_POSTAL_CEP = '#CepButton-ArrowID'
    this.BTN_LOCATION = '.lojaobramax-region-0-x-myLocation__geoMylocation'
    this.BTN_CHANGE_REGION = '.lojaobramax-region-0-x-cepPopOver__changeButton'
    this.BTN_REGION = '.lojaobramax-region-0-x-geolocation__addressContainerRow'
    this.BTN_POSTAL_PERSON = '.lojaobramax-region-qta-0-x-region-app__postal-code-button'
    this.BTN_DROP_REGION = '.lojaobramax-region-0-x-selectInput__container > .vtex-button'
    this.SELLER_NAME_PERSON = '.lojaobramax-region-qta-0-x-region-app__seller-name'
    this.INPUT_REGION_CEP = '.lojaobramax-region-0-x-cepInput'
    this.INPUT_REGION_PERSON = '.lojaobramax-region-qta-0-x-region-app__postal-code-input'
    this.MODAL_BACKDROP = '.lojaobramax-region-0-x-backdrop'
    this.MODAL_REGION = '.lojaobramax-region-0-x-geolocation__modalContent'
    this.MODAL_SELECT_SELLER = '.lojaobramax-region-qta-0-x-region-app__change-select-label'
    this.BTN_DROP_SELLER = '.lojaobramax-region-qta-0-x-region-app__select-content-select-container > .flex'
    this.DROP_SELLER = 'select#lojas'
    this.TOAST_REGION = '.vtex-toast'
    this.TXT_REGION = '.lojaobramax-region-0-x-geolocation__regionAdressText'
    this.TXT_REGION_QTA = '.lojaobramax-region-qta-0-x-region-app__seller-name'
    this.DROP_REGION = 'select.o-0.absolute.top-0.left-0.h-100.w-100.bottom-0.t-body.pointer'
    this.POPUP_REGION_TITLE = '.lojaobramax-region-0-x-popup__title'
    this.POPUP_REGION_TEXT = '.lojaobramax-region-0-x-popup__overlay'
    this.MODAL_TOP_BAR = '.lojaobramax-region-0-x-geolocation__addressContainerRow'
    this.MODAL_TOP_BAR_OFFER = '.lojaobramax-region-0-x-geolocation__regionMessageText'
    this.MODAL_TOP_BAR_REGION = '.lojaobramax-region-0-x-geolocation__regionAdressText'
    this.MODAL_TOP_BAR_MODIFY = '.lojaobramax-region-0-x-cepPopOver__changeButton'
    this.MODAL_OVERLAY = '.lojaobramax-region-qta-0-x-region-app__overlay'
    this.MODAL_CALCULATE_SHIPPING = '.vtex-flex-layout-0-x-flexRowContent--shipping-simulator'
    this.MODAL_CALCULATE_SHIPPING_TITLE = '.vtex-rich-text-0-x-paragraph--shipping-simulator-title '
    this.TXT_SUCESS_TITLE = '.lojaobramax-shipping-simulator-0-x-shippingOptionsTitle'
    this.INPUT_ADDRESS = '.vtex-address-form-4-x-input'
    this.BTN_INPUT_ADDRESS = '.lojaobramax-shipping-simulator-0-x-shippingFormContainer > .vtex-button'
    this.TXT_WARNING = '.lojaobramax-shipping-simulator-0-x-shippingSimulatorWarningMessageContainer'
    this.TXT_ERROR = '.vtex-input__error'
  }
}
module.exports = REGION_PAGE
