const FOOTER_PAGE = require('../page_elements/footer_page')
const FOOTER_PG = new FOOTER_PAGE()
const HOME_PAGE = require('../page_elements/home_page')
const HOME_PG = new HOME_PAGE()
const validation_data = require('../../fixtures/footer.json')

Cypress.Commands.add('footer', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.DIV_FOOTER).should('exist').should('be.visible')
})
Cypress.Commands.add('footerMenuPolicy', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_POLICY)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_policy.title)
    .should('contain.text', validation_data.footer.menu_policy.txt_pagamento)
    .should('contain.text', validation_data.footer.menu_policy.txt_privacidade)
    .should('contain.text', validation_data.footer.menu_policy.txt_cookies)
    .should('contain.text', validation_data.footer.menu_policy.txt_troca)
    .should('contain.text', validation_data.footer.menu_policy.txt_entrega)
    .should('contain.text', validation_data.footer.menu_policy.txt_termos)
    .should('contain.text', validation_data.footer.menu_policy.txt_igualdade)
})
Cypress.Commands.add('footerMenuTitle', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_TITLE)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_title.title)
    .should('contain.text', validation_data.footer.menu_title.txt_certificacao)
    .should('contain.text', validation_data.footer.menu_title.txt_central)
    .should('contain.text', validation_data.footer.menu_title.txt_pagameto)
    .should('contain.text', validation_data.footer.menu_title.txt_redes)
})
Cypress.Commands.add('footerMenuSeller', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_MOOCA)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_stores_mooca.title)
    .should('contain.text', validation_data.footer.menu_stores_mooca.txt_address)
    .should('contain.text', validation_data.footer.menu_stores_mooca.txt_stores)
    .should('contain.text', validation_data.footer.menu_stores_mooca.txt_working_hours)
    .should('contain.text', validation_data.footer.menu_stores_mooca.txt_saturday_hours)
    .should('contain.text', validation_data.footer.menu_stores_mooca.txt_sunday_hours)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_PRAIA)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_stores_praia.title)
    .should('contain.text', validation_data.footer.menu_stores_praia.txt_address)
    .should('contain.text', validation_data.footer.menu_stores_praia.txt_stores)
    .should('contain.text', validation_data.footer.menu_stores_praia.txt_working_hours)
    .should('contain.text', validation_data.footer.menu_stores_praia.txt_sunday_hours)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_BENFICA)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_stores_benfica.title)
    .should('contain.text', validation_data.footer.menu_stores_benfica.txt_address)
    .should('contain.text', validation_data.footer.menu_stores_benfica.txt_stores)
    .should('contain.text', validation_data.footer.menu_stores_benfica.txt_working_hours)
    .should('contain.text', validation_data.footer.menu_stores_benfica.txt_sunday_hours)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_PIRACICABA)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_stores_piracicaba.title)
    .should('contain.text', validation_data.footer.menu_stores_piracicaba.txt_address)
    .should('contain.text', validation_data.footer.menu_stores_piracicaba.txt_stores)
    .should('contain.text', validation_data.footer.menu_stores_piracicaba.txt_working_hours)
    .should('contain.text', validation_data.footer.menu_stores_piracicaba.txt_sunday_hours)
})
Cypress.Commands.add('footerMenu', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_TELE_VENDA)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_tele_venda.title)
    .should('contain.text', validation_data.footer.menu_tele_venda.txt_contact)
    .should('contain.text', validation_data.footer.menu_tele_venda.txt_working_hours)
    .should('contain.text', validation_data.footer.menu_tele_venda.txt_sunday_hours)
    .should('contain.text', validation_data.footer.menu_tele_venda.txt_saturday_hours)
    .should('contain.text', validation_data.footer.menu_tele_venda.txt_budget)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_CENTRAL_CLIENTE)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_central_cliente.title)
    .should('contain.text', validation_data.footer.menu_central_cliente.txt_contact)
    .should('contain.text', validation_data.footer.menu_central_cliente.txt_working_hours)
    .should('contain.text', validation_data.footer.menu_central_cliente.txt_sunday_hours)
    .should('contain.text', validation_data.footer.menu_central_cliente.txt_saturday_hours)
    .should('contain.text', validation_data.footer.menu_central_cliente.txt_budget)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_FAQ)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_faq.txt_help)
    .should('contain.text', validation_data.footer.menu_faq.txt_questions)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_CONTEUDO)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_conteudo.title)
    .should('contain.text', validation_data.footer.menu_conteudo.txt_academia)
    .should('contain.text', validation_data.footer.menu_conteudo.txt_blog)
    .should('contain.text', validation_data.footer.menu_conteudo.txt_obra)
})
Cypress.Commands.add('footerCopyRicht', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.DIV_COPYRIGHT)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.copyright.title)
    .should('contain.text', validation_data.footer.copyright.txt_informative_on)
    .should('contain.text', validation_data.footer.copyright.txt_informative_middle)
    .should('contain.text', validation_data.footer.copyright.txt_informativelast)
})
Cypress.Commands.add('footerImagens', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_FACEBOOK)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_YOUTUBE)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_INSTAGRAM)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_LINKEDIN)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_TWITTER)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_TIK_TOK)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)

  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_GOOGLE_RATING)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_SELO_RECLAME_AQUI)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_SELO_EBIT)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_PIX)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MG_SVG_BOLETO)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_DEPOSITO)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_VISA)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_VISA_ELETRON)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_MASTER)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_MAESTRO)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_DINERS)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_AMERICAN_EXPRESS)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_HIPERCARD)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_ELO)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_CONSTRUCARD)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_QUALITY)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.IMG_SVG_VTEX)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
})
Cypress.Commands.add('footerInstitutional', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.DIV_FOOTER).should('exist').should('be.visible')
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.MENU_INSTITUTIONAL)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_institutional.title)
    .should('contain.text', validation_data.footer.menu_institutional.txt_quem_somos)
    .should('contain.text', validation_data.footer.menu_institutional.txt_trabalhe_conosco)
    .should('contain.text', validation_data.footer.menu_institutional.txt_assessoria)
    .should('contain.text', validation_data.footer.menu_institutional.txt_fornecedores)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.BTN_BACK_TO)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
    .click()
  cy.get(HOME_PG.IMG_BANNER_HOME).should('be.visible').should('exist').find('img').should('exist')
})
Cypress.Commands.add('footerMobile', () => {
  cy.get(FOOTER_PG.SECTION_COPYRIGHT_MOBILE.DIV_FOOTER).should('exist').should('be.visible')
  cy.get(FOOTER_PG.SECTION_COPYRIGHT_MOBILE.DIV_FOOTER)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.menu_policy.title)
    .should('contain.text', validation_data.footer.menu_title.title)
    .should('contain.text', validation_data.footer.menu_title.txt_central)
    .should('contain.text', validation_data.footer.menu_faq.txt_help)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.DIV_FOOTER)
    .should('exist')
    .should('be.visible')
    .should('contain.text', validation_data.footer.copyright.title)
    .should('contain.text', validation_data.footer.copyright.txt_informative_on)
    .should('contain.text', validation_data.footer.copyright.txt_informative_middle)
    .should('contain.text', validation_data.footer.copyright.txt_informativelast)
  cy.get(FOOTER_PG.SECTION_COPYRIGHT.BTN_BACK_TO)
    .should('exist')
    .should('be.visible')
    .should('have.length', 1)
    .click()
  cy.get(HOME_PG.IMG_BANNER_HOME).should('be.visible').should('exist').find('img').should('exist')
})
